### ISSUE TITLE
getCssData doesn't respect page's <base> href when building URLs for CSS download

### ISSUE THREAD

**Issue by bobrosoft** [jhildenbiddle/get-css-data#3]
Hi, I'm using `css-vars-ponyfill` which using `get-css-data` and I found that page's `<base>` tag's href not taken into account when it downloads CSS sources by JS. Fortunately `css-vars-ponyfill` provides `onBeforeSend` hook and I was able to solve that issue in the next way:
```
cssVars({
  updateURLs: false,
  onBeforeSend: function(xhr, elm, url) {
    var baseUrl = document.querySelector('base').getAttribute('href');
    xhr.open('GET', url.replace(location.origin + '/', baseUrl)); // fix to respect base URL
  }
});
```

Wrong URL requested was: https://mydomain/1.css
Correct URL should be: https://cdn.something.com/mydomain/1.css (because of `<base href="https://cdn.something.com/mydomain/">`)

**Comment by jhildenbiddle** [comment]
@bobrosoft --

This issue has been addressed in the 1.7.0 release. Note that you will likely need to remove the `onBeforeSend` behavior listed above if/when you update to 1.7.0.

FWIW, this one is tough to create an automated test for due to Idiosyncrasies with the HTML `<base>` tag. One easy way to do it is to paste the following HTML into https://htmledit.squarefree.com/

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <base href="https://unpkg.com/get-css-data@1.7.0/tests/fixtures/">
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="style1.css">
</head>
<body>
    <script src="https://unpkg.com/get-css-data@1.7.0/dist/get-css-data.min.js"></script>
    <script>
        function show(msg) {
            document.body.innerHTML += '<p>' + msg + '</p>';
        }

        getCssData({
            onBeforeSend: function(xhr, node, url) {
                show('onBeforeSend: ' + url);
            },
            onSuccess: function(cssText, node, url) {
                show('onSuccess: ' + url);
            },
            onComplete: function(cssText, cssArray, nodeArray) {
                show(cssText);
            }
        });
    </script>
</body>
</html>
```

Thanks for filing the issue!
